source 'https://rubygems.org'

gem 'sinatra',        '~> 3.2'
gem 'sinatra-contrib','~> 3.2'
gem 'puma',           '~> 6.4'
gem 'pg',             '~> 1.5'
gem 'activerecord',   '~> 7.1'
gem 'datadog',        '~> 2.3'
gem 'json',           '~> 2.7'
