#!/bin/bash
# setup-java-full.sh — cria estrutura e popula todos os arquivos

set -e

BASE="$HOME/datadog-monitoring/java"

echo ">>> Criando diretorios..."
mkdir -p "$BASE/.mvn/wrapper"
mkdir -p "$BASE/src/main/java/com/example/crud/model"
mkdir -p "$BASE/src/main/java/com/example/crud/repository"
mkdir -p "$BASE/src/main/java/com/example/crud/controller"
mkdir -p "$BASE/src/main/resources"
mkdir -p "$BASE/src/test/java/com/example/crud"

echo ">>> Criando arquivos vazios..."
touch "$BASE/pom.xml"
touch "$BASE/mvnw"
touch "$BASE/run-local.sh"
touch "$BASE/.mvn/wrapper/maven-wrapper.properties"
touch "$BASE/src/main/java/com/example/crud/Application.java"
touch "$BASE/src/main/java/com/example/crud/model/Product.java"
touch "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
touch "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
touch "$BASE/src/main/resources/application.yml"
touch "$BASE/src/test/java/com/example/crud/ApplicationTest.java"

# =============================================================================
echo ">>> Populando: maven-wrapper.properties"
# =============================================================================
echo 'distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.zip' >> "$BASE/.mvn/wrapper/maven-wrapper.properties"
echo 'wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar' >> "$BASE/.mvn/wrapper/maven-wrapper.properties"

# =============================================================================
echo ">>> Populando: mvnw"
# =============================================================================
echo '#!/bin/sh' >> "$BASE/mvnw"
echo 'set -e' >> "$BASE/mvnw"
echo 'MAVEN_WRAPPER_PROPERTIES=".mvn/wrapper/maven-wrapper.properties"' >> "$BASE/mvnw"
echo 'MAVEN_HOME="$HOME/.m2/wrapper/dists/apache-maven-3.9.6"' >> "$BASE/mvnw"
echo 'if [ ! -d "$MAVEN_HOME" ]; then' >> "$BASE/mvnw"
echo '  echo "Downloading Maven 3.9.6..."' >> "$BASE/mvnw"
echo '  mkdir -p "$MAVEN_HOME"' >> "$BASE/mvnw"
echo '  curl -fsSL "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.tar.gz" \' >> "$BASE/mvnw"
echo '    | tar -xz -C "$MAVEN_HOME" --strip-components=1' >> "$BASE/mvnw"
echo 'fi' >> "$BASE/mvnw"
echo 'exec "$MAVEN_HOME/bin/mvn" "$@"' >> "$BASE/mvnw"
chmod +x "$BASE/mvnw"

# =============================================================================
echo ">>> Populando: run-local.sh"
# =============================================================================
echo '#!/bin/bash' >> "$BASE/run-local.sh"
echo 'set -e' >> "$BASE/run-local.sh"
echo 'AGENT_JAR="dd-java-agent.jar"' >> "$BASE/run-local.sh"
echo 'if [ ! -f "$AGENT_JAR" ]; then' >> "$BASE/run-local.sh"
echo '  echo "Baixando dd-java-agent..."' >> "$BASE/run-local.sh"
echo '  curl -Lo "$AGENT_JAR" https://dtdg.co/latest-java-tracer' >> "$BASE/run-local.sh"
echo 'fi' >> "$BASE/run-local.sh"
echo 'echo "Compilando..."' >> "$BASE/run-local.sh"
echo './mvnw package -DskipTests -q' >> "$BASE/run-local.sh"
echo 'echo "Iniciando java-crud na porta 8080..."' >> "$BASE/run-local.sh"
echo 'java \' >> "$BASE/run-local.sh"
echo '  -javaagent:dd-java-agent.jar \' >> "$BASE/run-local.sh"
echo '  -Ddd.service=java-crud \' >> "$BASE/run-local.sh"
echo '  -Ddd.env=dev \' >> "$BASE/run-local.sh"
echo '  -Ddd.version=1.0.1 \' >> "$BASE/run-local.sh"
echo '  -Ddd.logs.injection=true \' >> "$BASE/run-local.sh"
echo '  -Ddd.dbm.propagation.mode=full \' >> "$BASE/run-local.sh"
echo '  -Ddd.appsec.enabled=false \' >> "$BASE/run-local.sh"
echo '  -Ddd.trace.agent.host=localhost \' >> "$BASE/run-local.sh"
echo '  -Ddd.trace.agent.port=8126 \' >> "$BASE/run-local.sh"
echo '  -jar target/app.jar' >> "$BASE/run-local.sh"
chmod +x "$BASE/run-local.sh"

# =============================================================================
echo ">>> Populando: pom.xml"
# =============================================================================
echo '<?xml version="1.0" encoding="UTF-8"?>' >> "$BASE/pom.xml"
echo '<project xmlns="http://maven.apache.org/POM/4.0.0"' >> "$BASE/pom.xml"
echo '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' >> "$BASE/pom.xml"
echo '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0' >> "$BASE/pom.xml"
echo '         https://maven.apache.org/xsd/maven-4.0.0.xsd">' >> "$BASE/pom.xml"
echo '  <modelVersion>4.0.0</modelVersion>' >> "$BASE/pom.xml"
echo '  <parent>' >> "$BASE/pom.xml"
echo '    <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '    <artifactId>spring-boot-starter-parent</artifactId>' >> "$BASE/pom.xml"
echo '    <version>3.3.0</version>' >> "$BASE/pom.xml"
echo '    <relativePath/>' >> "$BASE/pom.xml"
echo '  </parent>' >> "$BASE/pom.xml"
echo '  <groupId>com.example</groupId>' >> "$BASE/pom.xml"
echo '  <artifactId>crud</artifactId>' >> "$BASE/pom.xml"
echo '  <version>1.0.0</version>' >> "$BASE/pom.xml"
echo '  <name>java-crud-datadog</name>' >> "$BASE/pom.xml"
echo '  <description>Java CRUD com Datadog APM + DBM + Security</description>' >> "$BASE/pom.xml"
echo '  <properties>' >> "$BASE/pom.xml"
echo '    <java.version>21</java.version>' >> "$BASE/pom.xml"
echo '  </properties>' >> "$BASE/pom.xml"
echo '  <dependencies>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>spring-boot-starter-web</artifactId>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>spring-boot-starter-data-jpa</artifactId>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>spring-boot-starter-actuator</artifactId>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.postgresql</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>postgresql</artifactId>' >> "$BASE/pom.xml"
echo '      <scope>runtime</scope>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>com.datadoghq</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>dd-trace-api</artifactId>' >> "$BASE/pom.xml"
echo '      <version>1.36.0</version>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.projectlombok</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>lombok</artifactId>' >> "$BASE/pom.xml"
echo '      <optional>true</optional>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '    <dependency>' >> "$BASE/pom.xml"
echo '      <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '      <artifactId>spring-boot-starter-test</artifactId>' >> "$BASE/pom.xml"
echo '      <scope>test</scope>' >> "$BASE/pom.xml"
echo '    </dependency>' >> "$BASE/pom.xml"
echo '  </dependencies>' >> "$BASE/pom.xml"
echo '  <build>' >> "$BASE/pom.xml"
echo '    <finalName>app</finalName>' >> "$BASE/pom.xml"
echo '    <plugins>' >> "$BASE/pom.xml"
echo '      <plugin>' >> "$BASE/pom.xml"
echo '        <groupId>org.springframework.boot</groupId>' >> "$BASE/pom.xml"
echo '        <artifactId>spring-boot-maven-plugin</artifactId>' >> "$BASE/pom.xml"
echo '        <configuration>' >> "$BASE/pom.xml"
echo '          <excludes>' >> "$BASE/pom.xml"
echo '            <exclude>' >> "$BASE/pom.xml"
echo '              <groupId>org.projectlombok</groupId>' >> "$BASE/pom.xml"
echo '              <artifactId>lombok</artifactId>' >> "$BASE/pom.xml"
echo '            </exclude>' >> "$BASE/pom.xml"
echo '          </excludes>' >> "$BASE/pom.xml"
echo '        </configuration>' >> "$BASE/pom.xml"
echo '      </plugin>' >> "$BASE/pom.xml"
echo '    </plugins>' >> "$BASE/pom.xml"
echo '  </build>' >> "$BASE/pom.xml"
echo '</project>' >> "$BASE/pom.xml"

# =============================================================================
echo ">>> Populando: Application.java"
# =============================================================================
echo 'package com.example.crud;' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo 'import org.springframework.boot.SpringApplication;' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo 'import org.springframework.boot.autoconfigure.SpringBootApplication;' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '@SpringBootApplication' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo 'public class Application {' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '    public static void main(String[] args) {' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '        SpringApplication.run(Application.class, args);' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/Application.java"
echo '}' >> "$BASE/src/main/java/com/example/crud/Application.java"

# =============================================================================
echo ">>> Populando: Product.java"
# =============================================================================
echo 'package com.example.crud.model;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import jakarta.persistence.*;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import lombok.Data;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import lombok.NoArgsConstructor;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import lombok.AllArgsConstructor;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import org.hibernate.annotations.CreationTimestamp;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import org.hibernate.annotations.UpdateTimestamp;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'import java.time.LocalDateTime;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '@Entity' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '@Table(name = "products")' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '@Data' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '@NoArgsConstructor' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '@AllArgsConstructor' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo 'public class Product {' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Id' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @GeneratedValue(strategy = GenerationType.IDENTITY)' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private Long id;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(nullable = false, length = 100)' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private String name;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(length = 50)' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private String category = "general";' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(nullable = false)' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private Double price;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(columnDefinition = "integer default 0")' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private Integer stock = 0;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @CreationTimestamp' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(name = "created_at", updatable = false)' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private LocalDateTime createdAt;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @UpdateTimestamp' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    @Column(name = "updated_at")' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '    private LocalDateTime updatedAt;' >> "$BASE/src/main/java/com/example/crud/model/Product.java"
echo '}' >> "$BASE/src/main/java/com/example/crud/model/Product.java"

# =============================================================================
echo ">>> Populando: ProductRepository.java"
# =============================================================================
echo 'package com.example.crud.repository;' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo '' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo 'import com.example.crud.model.Product;' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo 'import org.springframework.data.jpa.repository.JpaRepository;' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo 'import org.springframework.stereotype.Repository;' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo '' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo '@Repository' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo 'public interface ProductRepository extends JpaRepository<Product, Long> {' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"
echo '}' >> "$BASE/src/main/java/com/example/crud/repository/ProductRepository.java"

# =============================================================================
echo ">>> Populando: ProductController.java"
# =============================================================================
echo 'package com.example.crud.controller;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import com.example.crud.model.Product;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import com.example.crud.repository.ProductRepository;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import datadog.trace.api.Trace;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import io.opentracing.Span;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import io.opentracing.util.GlobalTracer;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.slf4j.Logger;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.slf4j.LoggerFactory;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.springframework.beans.factory.annotation.Autowired;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.springframework.http.HttpStatus;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.springframework.http.ResponseEntity;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import org.springframework.web.bind.annotation.*;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import java.util.List;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'import java.util.Map;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '@RestController' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '@RequestMapping' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo 'public class ProductController {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    private static final Logger log = LoggerFactory.getLogger(ProductController.class);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Autowired' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    private ProductRepository repository;' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @GetMapping("/health")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<?> health() {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return ResponseEntity.ok(Map.of("status","ok","service","java-crud","version","1.0.0"));' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @GetMapping("/products")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Trace(operationName = "products.list", resourceName = "GET /products")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<List<Product>> listProducts() {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Span span = GlobalTracer.get().activeSpan();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        List<Product> products = repository.findAll();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (span != null) span.setTag("results.count", products.size());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        log.info("Listed {} products", products.size());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return ResponseEntity.ok(products);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @GetMapping("/products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Trace(operationName = "products.get", resourceName = "GET /products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<Product> getProduct(@PathVariable Long id) {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Span span = GlobalTracer.get().activeSpan();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (span != null) span.setTag("product.id", id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return repository.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @PostMapping("/products")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Trace(operationName = "products.create", resourceName = "POST /products")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<Product> createProduct(@RequestBody Product product) {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Span span = GlobalTracer.get().activeSpan();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (product.getCategory() == null) product.setCategory("general");' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (product.getStock() == null) product.setStock(0);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Product saved = repository.save(product);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (span != null) { span.setTag("product.id", saved.getId()); span.setTag("product.name", saved.getName()); }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        log.info("Created product id={} name={}", saved.getId(), saved.getName());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return ResponseEntity.status(HttpStatus.CREATED).body(saved);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @PutMapping("/products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Trace(operationName = "products.update", resourceName = "PUT /products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<Product> updateProduct(@PathVariable Long id, @RequestBody Product updated) {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Span span = GlobalTracer.get().activeSpan();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (span != null) span.setTag("product.id", id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return repository.findById(id).map(existing -> {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            if (updated.getName()     != null) existing.setName(updated.getName());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            if (updated.getCategory() != null) existing.setCategory(updated.getCategory());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            if (updated.getPrice()    != null) existing.setPrice(updated.getPrice());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            if (updated.getStock()    != null) existing.setStock(updated.getStock());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            log.info("Updated product id={}", id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '            return ResponseEntity.ok(repository.save(existing));' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        }).orElse(ResponseEntity.notFound().build());' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @DeleteMapping("/products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    @Trace(operationName = "products.delete", resourceName = "DELETE /products/{id}")' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    public ResponseEntity<?> deleteProduct(@PathVariable Long id) {' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        Span span = GlobalTracer.get().activeSpan();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (span != null) span.setTag("product.id", id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        if (!repository.existsById(id)) return ResponseEntity.notFound().build();' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        repository.deleteById(id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        log.info("Deleted product id={}", id);' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '        return ResponseEntity.ok(Map.of("message", "Product " + id + " deleted"));' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '    }' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"
echo '}' >> "$BASE/src/main/java/com/example/crud/controller/ProductController.java"

# =============================================================================
echo ">>> Populando: application.yml"
# =============================================================================
echo 'spring:' >> "$BASE/src/main/resources/application.yml"
echo '  application:' >> "$BASE/src/main/resources/application.yml"
echo '    name: java-crud' >> "$BASE/src/main/resources/application.yml"
echo '  datasource:' >> "$BASE/src/main/resources/application.yml"
echo '    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/crud_db}' >> "$BASE/src/main/resources/application.yml"
echo '    username: ${DB_USER:crud_user}' >> "$BASE/src/main/resources/application.yml"
echo '    password: ${DB_PASSWORD:crud_pass}' >> "$BASE/src/main/resources/application.yml"
echo '    hikari:' >> "$BASE/src/main/resources/application.yml"
echo '      maximum-pool-size: 10' >> "$BASE/src/main/resources/application.yml"
echo '      minimum-idle: 2' >> "$BASE/src/main/resources/application.yml"
echo '  jpa:' >> "$BASE/src/main/resources/application.yml"
echo '    hibernate:' >> "$BASE/src/main/resources/application.yml"
echo '      ddl-auto: update' >> "$BASE/src/main/resources/application.yml"
echo '    show-sql: false' >> "$BASE/src/main/resources/application.yml"
echo '    properties:' >> "$BASE/src/main/resources/application.yml"
echo '      hibernate:' >> "$BASE/src/main/resources/application.yml"
echo '        dialect: org.hibernate.dialect.PostgreSQLDialect' >> "$BASE/src/main/resources/application.yml"
echo 'server:' >> "$BASE/src/main/resources/application.yml"
echo '  port: ${PORT:8080}' >> "$BASE/src/main/resources/application.yml"
echo 'logging:' >> "$BASE/src/main/resources/application.yml"
echo '  level:' >> "$BASE/src/main/resources/application.yml"
echo '    root: INFO' >> "$BASE/src/main/resources/application.yml"
echo '    com.example.crud: DEBUG' >> "$BASE/src/main/resources/application.yml"
echo 'management:' >> "$BASE/src/main/resources/application.yml"
echo '  endpoints:' >> "$BASE/src/main/resources/application.yml"
echo '    web:' >> "$BASE/src/main/resources/application.yml"
echo '      exposure:' >> "$BASE/src/main/resources/application.yml"
echo '        include: health,info,metrics' >> "$BASE/src/main/resources/application.yml"

# =============================================================================
echo ">>> Populando: ApplicationTest.java"
# =============================================================================
echo 'package com.example.crud;' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo '' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo 'import org.junit.jupiter.api.Test;' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo '' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo 'class ApplicationTest {' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo '    @Test' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo '    void contextLoads() {}' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"
echo '}' >> "$BASE/src/test/java/com/example/crud/ApplicationTest.java"

# =============================================================================
echo ""
echo ">>> Estrutura final:"
tree "$BASE"
echo ""
echo ">>> Pronto! Para compilar e subir:"
echo "    cd $BASE"
echo "    ./run-local.sh"