name: DORA Monitoring Pipeline

on:
  push:
    branches:
      - main

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose -f docker/docker-compose.yml build

      - name: Start environment
        run: docker compose -f docker/docker-compose.yml up -d
      
      - name: Wait services
        run: sleep 25

      - name: Fix permissions
        run: chmod +x scripts/*.sh

      - name: Run traffic tests
        run: |
          ./scripts/test-crud.sh
        
      - name: Stop environment
        if: always()
        run: docker compose -f docker/docker-compose.yml down -v

      - name: Dump logs
        if: failure()
        run: docker compose -f docker/docker-compose.yml logs

      - name: Docker system prune
        if: always()
        run: docker system prune -af

      - name: Send custom deployment event to Datadog
        run: |
          curl -X POST "https://api.datadoghq.com/api/v1/events" \
          -H "Content-type: application/json" \
          -H "DD-API-KEY: $DD_API_KEY" \
          -d '{
            "title": "Deployment executed",
            "text": "New deployment from GitHub Actions",
            "tags": ["env:lab","service:datadog-monitoring","dora:deployment"]
          }'
