name: DORA Monitoring Pipeline

on:
  push:
    branches:
      - main

env:
  DD_API_KEY: ${{ secrets.DD_API_KEY }}

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Record deploy start time
        id: deploy_start
        run: echo "started_at=$(date -u +%s)" >> $GITHUB_OUTPUT

      - name: Build containers
        run: docker compose -f docker/docker-compose.yml build

      - name: Start environment
        run: docker compose -f docker/docker-compose.yml up -d

      - name: Install datadog-ci
        run: npm install -g @datadog/datadog-ci
      
      - name: Wait services
        run: sleep 25

      - name: Fix permissions
        run: chmod +x scripts/*.sh

      - name: Run traffic tests
        run: |
          ./scripts/test-crud.sh
        
      - name: Stop environment
        if: always()
        run: docker compose -f docker/docker-compose.yml down -v

      - name: Dump logs
        if: failure()
        run: docker compose -f docker/docker-compose.yml logs

      - name: Docker system prune
        if: always()
        run: docker system prune -af

      - name: DORA — Deploy sucesso
        if: success()
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: datadoghq.com
        run: |
          datadog-ci dora deployment \
            --service nodejs-crud \
            --env lab \
            --started-at ${{ steps.deploy_start.outputs.started_at }} \
            --finished-at $(date -u +%s) \
            --git-repository-url https://github.com/SilvaDan38/datadog-monitoring \
            --git-commit-sha ${{ github.sha }}

      - name: DORA — Deploy falha
        if: failure()
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: datadoghq.com
        run: |
          datadog-ci dora deployment \
            --service nodejs-crud \
            --env lab \
            --started-at ${{ steps.deploy_start.outputs.started_at }} \
            --finished-at $(date -u +%s) \
            --git-repository-url https://github.com/SilvaDan38/datadog-monitoring \
            --git-commit-sha ${{ github.sha }} \
            --is-failure
